### PR TITLE
Separate width and height parameters for Image widgets

### LINKED ISSUE #175: Constraining one dimension of a NetworkImage should be more ergonomic
I want to constrain an image's height and use the intrinsic width. This is what I tried:
```dart
new NetworkImage(
    src: message.url, size: const Size.fromHeight(120.0));
```
The width became infinite which was unexpected.

@abarth found that this does what I want:
```dart
new NetworkImage(
    src: message.url, size: const Size(null, 120.0));
```

Seems like the API could be more self-documenting somehow.

### PR DESCRIPTION
**Pull request by abarth**
This change makes it easier to defined only the width or the height of an image
and let the other value be filled in from the image's intrinsic aspect ratio.

Fixes #175

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
lgtm

File: sky/sdk/example/widgets/container.dart [hunk 1]
```diff
@@ -16,7 +16,8 @@ class ContainerApp extends App {
           decoration: new BoxDecoration(backgroundColor: const Color(0xFFCCCCCC)),
           child: new NetworkImage(
             src: "https://www.dartlang.org/logos/dart-logo.png",
-            size: new Size(300.0, 300.0)
+            width: 300.0,
+            height: 300.0
```
Comment (Hixie) [inline sky/sdk/example/widgets/container.dart]: it's sad that this ends up happening, but i don't see a better solution
