### PR TITLE
Fix the crash for buttons.

### LINKED ISSUE #277: _scaleAlpha null deref when tapping a dialog button
i just got the following crash while tapping on a button in a dialog: 

```
E/chromium(27216): [ERROR:dart_error.cc(19)] Unhandled exception:
E/chromium(27216): Uncaught Error: The null object does not have a getter 'alpha'.
E/chromium(27216):
E/chromium(27216): NoSuchMethodError: method not found: 'alpha'
E/chromium(27216): Receiver: null
E/chromium(27216): Arguments: []
E/chromium(27216): Stack Trace:
E/chromium(27216): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
E/chromium(27216): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
E/chromium(27216): #2      _scaleAlpha (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/base/lerp.dart:18:25)
E/chromium(27216): #3      lerpColor (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/base/lerp.dart:27:12)
E/chromium(27216): #4      lerpBoxDecoration (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/painting/box_painter.dart:277:22)
E/chromium(27216): #5      AnimatedBoxDecorationValue.setProgress (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/animated_container.dart:34:13)
E/chromium(27216): #6      AnimationPerformance._tick (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/animation/animation_performance.dart:82:14)
E/chromium(27216): #7      Timeline._tick (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/animation/timeline.dart:77:12)
E/chromium(27216): #8      AnimatedSimulation.value= (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/animation/animated_simulation.dart:82:12)
E/chromium(27216): #9      Timeline.value= (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/animation/timeline.dart:46:16)
E/chromium(27216): #10     AnimationPerformance.progress= (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/animation/animation_performance.dart:34:14)
E/chromium(27216): #11     ImplicitlyAnimatedValue.value= (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/animated_container.dart:72:11)
E/chromium(27216): #12     AnimatedContainer._updateField (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/animated_container.dart:137:21)
E/chromium(27216): #13     AnimatedContainer._updateDecoration (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/animated_container.dart:150:5)
E/chromium(27216): #14     AnimatedContainer._updateFields (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/animated_container.dart:127:5)
E/chromium(27216): #15     AnimatedContainer.syncFields (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/animated_container.dart:122:5)
E/chromium(27216): #16     StatefulComponent._sync (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:692:7)
E/chromium(27216): #17     Widget.syncChild (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:304:19)
E/chromium(27216): #18     Component._sync (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:619:14)
E/chromium(27216): #19     Widget.syncChild (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:321:13)
E/chromium(27216): #20     OneChildRenderObjectWrapper.syncRenderObject (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:924:14)
E/chromium(27216): #21     SizedBox.syncRenderObject (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/basic.dart:200:27)
E/chromium(27216): #22     RenderObjectWrapper._sync (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:849:5)
E/chromium(27216): #23     Widget.syncChild (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:321:13)
E/chromium(27216): #24     OneChildRenderObjectWrapper.syncRenderObject (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:924:14)
E/chromium(27216): #25     ConstrainedBox.syncRenderObject (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/basic.dart:215:27)
E/chromium(27216): #26     RenderObjectWrapper._sync (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:849:5)
E/chromium(27216): #27     Widget.syncChild (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:321:13)
E/chromium(27216): #28     OneChildRenderObjectWrapper.syncRenderObject (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:924:14)
E/chromium(27216): #29     Padding.syncRenderObject (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/basic.dart:165:27)
E/chromium(27216): #30     RenderObjectWrapper._sync (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:849:5)
E/chromium(27216): #31     Widget.syncChild (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:321:13)
E/chromium(27216): #32     Component._sync (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:619:14)
E/chromium(27216): #33     Widget.syncChild (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:321:13)
E/chromium(27216): #34     TagNode._sync (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:380:13)
E/chromium(27216): #35     Widget.syncChild (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:321:13)
E/chromium(27216): #36     TagNode._sync (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:380:13)
E/chromium(27216): #37     Widget.syncChild (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:321:13)
E/chromium(27216): #38     StatefulComponent.syncChild (/usr/local/google/home/ianh/dev/sky_engine/src/sky/sdk/lib/widgets/widget.dart:709:27)
...```

@collinjackson says he's seen this too.

### PR DESCRIPTION
**Pull request by Hixie**
Turns out that we were trying to lerp between null colours.

Fixes #277.

### CODE REVIEW

File: sky/sdk/lib/painting/box_painter.dart [hunk 1]
```diff
@@ -274,7 +280,7 @@ BoxDecoration lerpBoxDecoration(BoxDecoration a, BoxDecoration b, double t) {
     return a.scale(1.0 - t);
   // TODO(abarth): lerp ALL the fields.
   return new BoxDecoration(
-    backgroundColor: lerpColor(a.backgroundColor, b.backgroundColor, t),
+    backgroundColor: lerpColor(unnullColor(a.backgroundColor), unnullColor(b.backgroundColor), t),
```
Comment (abarth) [inline sky/sdk/lib/painting/box_painter.dart]: We should put this logic in lerpColor.

**Comment by collinjackson** [comment]
lgtm
